### ISSUE TITLE
Licensing: RAT excludes

### ISSUE THREAD

**Issue by wesm** [graphistry/arrow#4]
I created a branch here to assist with license auditing: https://github.com/wesm/arrow-1/tree/rat

to run it, do

```
git archive HEAD --prefix=arrow/ --output=arrow-src.tar.gz
run-rat.sh arrow-src.tar.gz
```

I see:

```
$ ./run-rat.sh arrow-src.tar.gz 
NOT APPROVED: .eslintrc (arrow/.eslintrc): false
NOT APPROVED: .travis.yml (arrow/.travis.yml): false
NOT APPROVED: CHANGELOG.md (arrow/CHANGELOG.md): false
NOT APPROVED: closure-compiler/flatbuffers.js (arrow/closure-compiler/flatbuffers.js): false
NOT APPROVED: closure-compiler/text-encoding.js (arrow/closure-compiler/text-encoding.js): false
NOT APPROVED: closure-compiler/tslib.js (arrow/closure-compiler/tslib.js): false
NOT APPROVED: develop.md (arrow/develop.md): false
```

Could you advise on the licensing for these files? If they originate from other projects, can you add the associated licenses at the end of your LICENSE file? 

Is there any other code in the project (to your knowledge) that originated from another project that will need to be noted in LICENSE file?

Thanks!

**Comment by trxcllnt** [comment]
@wesm ah looks like I forgot a few headers

`develop.md` - ours, will add header
`.travis.yml` - Travis-CI config, will add header
`.eslintrc` - old config file, no longer needed, will delete.
`CHANGELOG.md` - auto-generated by command line tools from git commit history (not sure if I can configure to add license header, but will look into it)

The files in the `closure-compiler` dir are libraries that we had to copy and [add `goog.module` calls](https://github.com/graphistry/arrow/blob/master/closure-compiler/flatbuffers.js#L12) to make the Google Closure Compiler build work. 
- flatbuffers
  - source: [code](https://github.com/google/flatbuffers/blob/master/js/flatbuffers.js) 
  - license: [Apache 2.0](https://github.com/google/flatbuffers/blob/master/LICENSE.txt)

- text-encoding
  - source: [code](https://github.com/arv/text-encoding-utf-8/blob/master/lib/encoding.cjs.js)
  - license: [unlicense](https://github.com/arv/text-encoding-utf-8/blob/master/LICENSE.md)

- tslib
  - source: [code](https://github.com/Microsoft/tslib/blob/master/tslib.js)
  - license: [Apache 2.0](https://github.com/Microsoft/tslib/blob/master/LICENSE.txt)

Should I append all their licenses to our LICENSE.md file in the repo? Or just the unlicense text?

**Comment by wesm** [comment]
Cool, with text-encoding I think in the header it says public domain so that one is OK, no need to amend LICENSE.md. The others should have entries in LICENSE not unlike https://github.com/apache/arrow/blob/master/LICENSE.txt#L347; we can append these to the Arrow LICENSE.txt when importing the code

OK to leave CHANGELOG.md as is

**Comment by trxcllnt** [comment]
@wesm great, thanks. does this look good? https://github.com/graphistry/arrow/blob/master/LICENSE#L203

**Comment by wesm** [comment]
Perfect, thanks!
